meta:
  schema-version: 0.1.0
  created-on: "2024-05-30T08:56:30Z"
  cli-version: 0.2.0
projects:
  protobuf-js-5137-test:
    targets:
      - package.json
    manager:
      ecosystem: node
      name: npm
      version: "5"
    overrides:
      decode-uri-component:
        0.2.0:
          use: 0.2.0-sp1
      glob-parent:
        3.1.0:
          use: 3.1.0-sp1
      semver:
        6.3.0:
          use: 6.3.0-sp1
        5.7.1:
          use: 5.7.1-sp1
        7.3.2:
          use: 7.3.2-sp1
      word-wrap:
        1.2.3:
          use: 1.2.3-sp1
      minimist:
        1.2.5:
          use: 1.2.5-sp1
      json5:
        2.1.3:
          use: 2.1.3-sp1
      ansi-regex:
        4.1.0:
          use: 4.1.0-sp1
        5.0.0:
          use: 5.0.0-sp1
      async:
        2.6.3:
          use: 2.6.3-sp1
      y18n:
        4.0.0:
          use: 4.0.0-sp1
      lodash.template:
        4.5.0:
          use: 4.5.0-sp1
      minimatch:
        3.0.4:
          use: 3.0.4-sp1
      ini:
        1.3.5:
          use: 1.3.5-sp1
      tar:
        4.4.13:
          use: 4.4.13-sp1
